language: ruby
cache: bundler
rvm:
- 2.1.0
sudo: false
deploy:
  edge:
    source: criteo-forks/dpl
    branch: chef_supermarket_dependency_on_mime_type
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Package Management
  client_key: .travis/client.pem
  on:
    tags: true
    all_branches: true
before_deploy:
- rvm 1.9.3 --fuzzy do ruby -S gem install json_pure
- openssl aes-256-cbc -K $encrypted_31f7c76bb631_key -iv $encrypted_31f7c76bb631_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
