language: ruby
cache: bundler
rvm:
- 2.3.0
sudo: false
deploy:
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Package Management
  client_key: .travis/client.pem
  skip_cleanup: true
  on:
    tags: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_31f7c76bb631_key -iv $encrypted_31f7c76bb631_iv
  -in .travis/client.pem.enc -out .travis/client.pem -d
