language: ruby
rvm:
- 2.1.0
deploy:
  edge: true
  provider: chef-supermarket
  user_id: criteo
  cookbook_category: Package Management
  client_key: ".travis/client.pem"
  on:
    tags: true
    all_branches: true
before_deploy:
- openssl aes-256-cbc -K $encrypted_31f7c76bb631_key -iv $encrypted_31f7c76bb631_iv
  -in .travis/client.pem.enc -out .travis/criteo.pem -d
